### PR TITLE
Stopped treating non-200 responses as error - fixes #1040

### LINKED ISSUE #1040: fakeServer is broken with .respond(500) on 1.17.4
Hi guys,

I'm using `karma-sinon` and it's always installing Sinon's latest version by default. It seems that the version 1.17.4 broke this for me:

`this.server.requests[0].respond(500, { 'Content-Type' : 'application/json' }, JSON.stringify({}));`

It won't call the error handler on my Ajax call. For some reason, I can't even find the tag for this version here on Github, to help debug the problem. As a workaround, I've downgraded to 1.17.3 and ran shrinkwrap on my project to be safe.

* Sinon version : 1.17.4
* Environment   : OSX
* Other libraries you are using: karma-sinon

**What did you expect to happen?**
Ajax error to be triggered.

**What actually happens**
I won't trigger my Ajax error handler.

**How to reproduce**
```
this.server = sinon.fakeServer.create();
this.server.requests[0].respond(500, { 'Content-Type' : 'application/json' }, JSON.stringify({}));
```

### PR DESCRIPTION
**Pull request by fearphage**
* non-200 requests trigger `load` event (fixes regression)
* added `xhr.error()` to simulate network errors

Tests and fixes are ported from `master`.

### CODE REVIEW

**Comment by fearphage** [comment]
This fixes #1040.

**Comment by fatso83** [comment]
👍 The code LGTM, on a casual (by-mobile) look :-) Re the actual implementation, I won't revisit the W3 spec, as I think the previous discussions has covered this in detail, so I'll just take your word for it doing what it should 😌

**Comment by fearphage** [comment]
It more closely emulates what browsers do now based on these simplified test cases.

http://people.mozilla.org/~mbanner2/sinonXHRBrowserTest.html

**Comment by fearphage** [comment]
This introduced a new bug (regression) that already exists in `master`.

Now progress events from non-200 responses don't have the right properties - `loaded`, `total`, `lengthComputable`.

I've filed it.  #1105

**Comment by fearphage** [comment]
I think this should ship broken (just like master). I'm working on a fix though.

Thoughts? 

Also as I am new here, do I need to wait for a few people or anyone in particular to weigh in on this fix before merging/releasing?

File: test/util/fake-xml-http-request-test.js [hunk 1]
```diff
@@ -1797,7 +1887,7 @@
 
             "triggers 'loadend' event at the end": function (done) {
                 this.xhr.addEventListener("loadend", function (e) {
-                    assertProgressEvent(e, 0);
```
Comment (fearphage) [inline test/util/fake-xml-http-request-test.js]: This test was correct and had to change based on the regression.

File: test/util/fake-xml-http-request-test.js [hunk 2]
```diff
@@ -1821,7 +1911,7 @@
 
             "calls #onloadend at the end": function (done) {
                 this.xhr.onloadend = function (e) {
-                    assertProgressEvent(e, 0);
```
Comment (fearphage) [inline test/util/fake-xml-http-request-test.js]: This test was correct and had to change based on the regression.

**Comment by fearphage** [comment]
I'm reconsidering now. Maybe we shouldn't exchange one regression for another one. I'm torn.

I have a possible fix (fearphage/Sinon.JS#1 -- ignore the repo and all), but I think maybe there's a middle ground there too.

**Comment by fatso83** [comment]
@fearphage Regarding merging: it depends. We haven't created any hard and fast rules. For minor fixes, we sometimes submit a PR (just to notify others), and then merge it ourselves. For bigger stuff, we usually wait for some input from the others.

Since you already have a nice fix, I don't see why we couldn't merge both this and your fix before releasing 1.17.5? @mantoni?

**Comment by fatso83** [comment]
@fearphage Merged. Care to make a PR with fearphage/Sinon.JS#1? I think it should be included in a 1.17.5 release. I could also do it of course, if you are unavailable, since I have a few days vacation that's not off-grid :-)
