### PR TITLE
Avoid installing setimmediate

### LINKED ISSUE #2085: Upgrade of Browserify fails tests
* Sinon version : `master` (before updating) or branch `bug-updating-deps`
* Environment   : Chromium

**What did you expect to happen?**
All tests pass in all environments.

**What actually happens**
One test fails.

```
  1360 passing (919ms)
  4 pending
  1 failing

  1) fakeTimers.clock
       .useFakeTimers
         fakes provided methods:
     AssertionError: [refute.same] function onNextTick() {} expected not to be the same object as function onNextTick() {}
      at Object.fail (node_modules/@sinonjs/referee/lib/create-fail.js:5)
      at Object.fail (node_modules/@sinonjs/referee/lib/define-assertion.js:46)
      at assertion (node_modules/@sinonjs/referee/lib/define-assertion.js:68)
      at Function.referee.<computed>.<computed> [as same] (node_modules/@sinonjs/referee/lib/define-assertion.js:93)
      at Context.<anonymous> (test/util/fake-timers-test.js:1075)
```

**How to reproduce**

Check out `master` (671330ce). Run `npm update && npm test`.

Also pushed the updates: https://github.com/sinonjs/sinon/commit/c8ff2b8f6f438ccac7c5c3abd9a106dc84914610

### PR DESCRIPTION
**Pull request by fatso83**
#### Purpose (TL;DR) - mandatory
This was an attempt at fixing #2085 (it doesn't), based on a suggestion in #2086.
Includes additional tests from #2086 by @mantoni (just rebased).

Even though it doesn't fix #2085, I guess it's still an improvement ... 

 #### Background (Problem in detail)  - optional
See #2085, #2086, sinonjs/lolex#268, sinonjs/lolex#269

 #### Solution  - optional
An underlying issue is fixed in Lolex: it tries to avoid the issues in #2085 simply by not installing setImmediate when the environment doesn't support it. Unfortunately it doesn't fix #2085, as it seems as this is actually caused by a browserify transform: https://github.com/browserify/insert-module-globals/releases/tag/v7.1.0. 

 #### How to verify - mandatory
1. Check out this branch
2. `npm install`
3. `npm t`

 #### Checklist for author

- [x] `npm run lint` passes

### CODE REVIEW

File: test/util/fake-timers-test.js [hunk 1]
```diff
@@ -102,72 +103,84 @@ describe("fakeTimers.clock", function() {
             this.clock = fakeTimers.clock.create();
         });
 
-        it("returns numeric id or object with numeric id", function() {
-            var result = this.clock.setImmediate(function() {
-                return;
-            });
+        if (typeof setImmediate === "function") {
```
Comment (fearphage) [inline test/util/fake-timers-test.js]: I wish we had a rule to detect this. This should be using `this.skip()` in the `before` instead of this.

Comment (mroderick) [reply test/util/fake-timers-test.js]: It shouldn't be that difficult to write an ESLint rule that detects when an `if` statement wraps an `it` invocation

Comment (fatso83) [reply test/util/fake-timers-test.js]: We had our reasons 🤷‍♂  https://github.com/sinonjs/sinon/pull/2086#discussion_r327539951
