### PR TITLE
Fix for `sinon.createFakeServer()` exception

### LINKED ISSUE #1531: sinon.createFakeServer() throws `TypeError: server.configure is not a function`
Sinon version: 3.2.0
Node version: 8.2.0

**To reproduce:**
```js
require("sinon").createFakeServer();
```

**Expected:**  
Fake server is created successfully.

**Actual:**
Error thrown `TypeError: server.configure is not a function`

**Analysis:**
When the function `createFakeServer` is [defined](https://github.com/sinonjs/sinon/blob/1b81ec67c30046f5117c9299faa24a66035d7fd5/lib/sinon.js#L32), the context of `nise.fakeServer` is not perserved.  
Instead, the context becomes the `sinon` object, which, as the error says, does not have a `configure` function.

**Suggested fix:**
`exports.createFakeServer = nise.fakeServer.create.bind(nise.fakeServer);`

**Temporary solution:**
Use `sinon.fakeServer.create()` instead.

### PR DESCRIPTION
**Pull request by EyalAr**
Fixes #1531 by preserving the context of `nise.fakeServer.create` and `nise.fakeServerWithClock.create`

### CODE REVIEW

File: test/sinon-test.js [hunk 1]
```diff
@@ -17,10 +17,14 @@ describe("sinon module", function () {
...
             fakeServer: {
-                create: "47c86a4c-6b48-4748-bb8c-d853f999720c"
+                create: function () {
+                    return "47c86a4c-6b48-4748-bb8c-d853f999720c";
+                }
             },
             fakeServerWithClock: {
-                create: "e69974f8-4568-48d1-a5e9-2b511a59c14b"
+                create: function () {
+                    "e69974f8-4568-48d1-a5e9-2b511a59c14b";
```
Comment (fatso83) [inline test/sinon-test.js]: This function will only return `undefined`. Add `return`.

**Comment by fatso83** [comment]
Thank you very much for this PR. This is good work, but there was just a minor issue that needs some fixing before merging this.

File: test/sinon-test.js (hunk 1 above)
Comment (EyalAr) [inline test/sinon-test.js]: Good catch. Fixed.

**Comment by mroderick** [comment]
Thank you 👍

**Comment by mroderick** [comment]
This was released with `sinon@3.2.1`
