### PR TITLE
Fixes #852: Do not attempt to re-stub constructors

### LINKED ISSUE #852: Sinon 1.17.0: sinon.createStubInstance cannot be used twice on the same constructor
This is a new issue in Sinon 1.17.0 and it's working fine with 1.16.1:

```js
var a = sinon.createStubInstance((MyThing);
var b = sinon.createStubInstance((MyThing);
```

Fails on the second line with:

```
TypeError: Attempted to wrap constructor which is already wrapped
  at checkWrappedMethod (node_modules/sinon/lib/sinon/util/core.js:91)
  at wrapMethod (node_modules/sinon/lib/sinon/util/core.js:121)
  at stub (node_modules/sinon/lib/sinon/stub.js:66)
  at node_modules/sinon/lib/sinon/stub.js:59
  at node_modules/sinon/lib/sinon/walk.js:34
  at forEach (null:null)
  at walk (node_modules/sinon/lib/sinon/walk.js:35)
  at walk (node_modules/sinon/lib/sinon/walk.js:39)
  at walk (node_modules/sinon/lib/sinon/walk.js:39)
  at stub (node_modules/sinon/lib/sinon/stub.js:61)
  at node_modules/sinon/lib/sinon/util/core.js:361
  ...
```

Environment: Node 4.0.0

### PR DESCRIPTION
**Pull request by traviskaufman**
Prevents walk was iterating over `constructor` which would essentially attempt to re-stub if `createStubInstance` was already called on the constructor or an instance of it.

### CODE REVIEW

File: test/issues/issues-test.js [hunk 1]
```diff
@@ -101,6 +101,30 @@
...
+        "#852 - createStubInstance on intherited constructors": {
+            "must not throw error": function () {
+                var A = function () {};
+                var B = function () {};
+
+                B.prototype = Object.create(A.prototype);
+                B.prototype.constructor = A;
+
+                refute.exception(function () {
+                    var b = sinon.createStubInstance(B); // eslint-disable-line no-unused-vars
```
Comment (mantoni) [inline test/issues/issues-test.js]: Why are you assigning the result to a variable? It's not used as your eslint comment suggests, right?

Comment (traviskaufman) [inline test/issues/issues-test.js]: yup you're right was copying the code from the issue (maybe a bit too quickly :)). Will fix.

**Comment by mantoni** [comment]
Thanks! LGTM (apart from the little thingy I noted inline). I can't think of a case where anyone would want the `constructor` property to be a stub. @cjohansen @mroderick @fatso83 any objections?

This includes the test from #854

**Comment by traviskaufman** [comment]
failing check looks like another false negative. @mantoni would you mind re-running the TravisCI job?

**Comment by mantoni** [comment]
Hm, apparently I can't control the Travis jobs under the new Sinon home. @cjohansen Can you check the permissions?

**Comment by mroderick** [comment]
I restarted the build, all is green now. @traviskaufman could you squash it down to just one commit please?

**Comment by traviskaufman** [comment]
@mroderick done.

**Comment by fatso83** [comment]
Looks good. No objections. I am actually hard pressed to come up with any good use of the constructor property in general :) 

PS . another failing negative in Travis. Perhaps the  failing test is a bit fragile? I am guessing some timing related issue.

**Comment by mroderick** [comment]
Sinon.JS v1.17.1 is now on npm, the website will be updated soon.
