### PR TITLE
Fixed #758 by checking the global variables are set

### LINKED ISSUE #758: Sinon breaks on import
Hi,

I have a project that uses sinon in unit tests. The project worked just fine could of days ago, and during that time I didn't change anything in it. Today I cloned it on a different machine, and tried running the tests again, but they now break with stack trace:

```
/Users/dominik/dev/testing-presentation/node_modules/sinon/lib/sinon/util/fake_xdomain_request.js:13
    undefined.sinon = {};
                    ^
TypeError: Cannot set property 'sinon' of undefined
    at Object.<anonymous> (/Users/dominik/dev/testing-presentation/node_modules/sinon/lib/sinon/util/fake_xdomain_request.js:13:15)
    at Module._compile (module.js:431:26)
    at normalLoader (/Users/dominik/dev/testing-presentation/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:160:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/dominik/dev/testing-presentation/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:173:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at loadDependencies (/Users/dominik/dev/testing-presentation/node_modules/sinon/lib/sinon/util/fake_server.js:228:9)
    at /Users/dominik/dev/testing-presentation/node_modules/sinon/lib/sinon/util/fake_server.js:238:9
    at Object.<anonymous> (/Users/dominik/dev/testing-presentation/node_modules/sinon/lib/sinon/util/fake_server.js:242:2)
    at Module._compile (module.js:431:26)
    at normalLoader (/Users/dominik/dev/testing-presentation/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:160:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/dominik/dev/testing-presentation/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:173:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at loadDependencies (/Users/dominik/dev/testing-presentation/node_modules/sinon/lib/sinon/util/fake_server_with_clock.js:89:9)
    at /Users/dominik/dev/testing-presentation/node_modules/sinon/lib/sinon/util/fake_server_with_clock.js:97:9
    at Object.<anonymous> (/Users/dominik/dev/testing-presentation/node_modules/sinon/lib/sinon/util/fake_server_with_clock.js:101:2)
    at Module._compile (module.js:431:26)
    at normalLoader (/Users/dominik/dev/testing-presentation/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:160:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/dominik/dev/testing-presentation/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:173:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at loadDependencies (/Users/dominik/dev/testing-presentation/node_modules/sinon/lib/sinon/sandbox.js:147:9)
    at /Users/dominik/dev/testing-presentation/node_modules/sinon/lib/sinon/sandbox.js:156:9
    at Object.<anonymous> (/Users/dominik/dev/testing-presentation/node_modules/sinon/lib/sinon/sandbox.js:162:2)
    at Module._compile (module.js:431:26)
    at normalLoader (/Users/dominik/dev/testing-presentation/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:160:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/dominik/dev/testing-presentation/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:173:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at loadDependencies (/Users/dominik/dev/testing-presentation/node_modules/sinon/lib/sinon.js:28:9)
    at /Users/dominik/dev/testing-presentation/node_modules/sinon/lib/sinon.js:39:9
    at Object.<anonymous> (/Users/dominik/dev/testing-presentation/node_modules/sinon/lib/sinon.js:46:2)
    at Module._compile (module.js:431:26)
    at normalLoader (/Users/dominik/dev/testing-presentation/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:160:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/dominik/dev/testing-presentation/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:173:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/dominik/dev/testing-presentation/test/unit/ValidationUtil-test.js:2:46)
    at Module._compile (module.js:431:26)
    at normalLoader (/Users/dominik/dev/testing-presentation/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:160:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/dominik/dev/testing-presentation/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:173:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /Users/dominik/dev/testing-presentation/node_modules/mocha/lib/mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/dominik/dev/testing-presentation/node_modules/mocha/lib/mocha.js:189:14)
    at Mocha.run (/Users/dominik/dev/testing-presentation/node_modules/mocha/lib/mocha.js:422:31)
    at Object.<anonymous> (/Users/dominik/dev/testing-presentation/node_modules/mocha/bin/_mocha:398:16)
    at Module._compile (module.js:431:26)
    at Object.Module._extensions..js (module.js:449:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:472:10)
    at startup (node.js:124:18)
    at node.js:959:3
```

The project I speak about is available at: https://github.com/domderen/testing-presentation

It looks to me like some sinon dependency got updated and it now breaks sinon during requireing. I'd appreciate any help on this one.

### PR DESCRIPTION
**Pull request by Serfenia**
By adding a function that checks if the 'window' or 'global' is set, it then picks corresponding one. This makes it work in a browser and Node.js (strict and non-strict). The strict mode caused the this pointer in the module to become undefined.

### CODE REVIEW

**Comment by Serfenia** [comment]
Sorry for the typo in the commit message. Should've been #758

**Comment by fatso83** [comment]
Thanks for your work. We appreciate all the help we can get! 

To fix the commit message: `git rebase -i origin/v1.17` and just replace 'pick' with 'r' (for reword). Then when you are satisfied, simply: `git push -f your-remote v1.17` to update the pull request.

But that is a minor issue. The bigger issue is that the [tests now fail](https://travis-ci.org/sinonjs/sinon/jobs/87911720) on our CI server:
```
Failed requiring ./test/assert-test.js: sinon.extend is not a function
```

**Comment by Serfenia** [comment]
Ah I see, but where does this go wrong? Because for me it's not really clear on what line of what file this goes wrong. Or even which particular test case.

**Comment by Serfenia** [comment]
The priority of the chosen global was wrong. Now `this` is chosen over `window` and `global`. I tested the implementation in [sinon-use-strict-native](https://github.com/Serfenia/sinon-use-strict-native) and the test does not break by sinon anymore.

**Comment by fatso83** [comment]
Now `npm test` passes and things are looking better :-) You'll still have to squash the commits into one commit before a merge happens, though.

The only thing I am wondering about is that this function seems somewhat "randomly" transplanted into `fake_xdomain_request.js`. Why this and not another? On the other hand, this is the v1.17 branch, so these minor issues might not matter all that much. Views on this, @mroderick ?

**Comment by Serfenia** [comment]
The reason I put it there was because the only place the error occurred was there. I have not experienced issues in other modules within sinon. I get your point though, but I don't have the knowdledge of sinon's structure to put it in a more suitable place. Do you have suggestions?

I will squash them in the morning tomorrow.

**Comment by fatso83** [comment]
I _totally_ understand that you don't have complete insight into every little bit of Sinon, and the fact that you went ahead and fixed the issue is a great thing. I don't have much of an idea where the best fit might be, which is why I thought Morgan or @mantoni might chime in. I would await rebasing until we have had some more time to look at this. I will have to wait until the weekend to have a proper look, myself.

**Comment by Serfenia** [comment]
Allright I'll leave it up to you then. Would be great to have it fixed after the weekend break :).

File: lib/sinon/util/fake_xdomain_request.js [hunk 1]
```diff
@@ -7,8 +7,24 @@
...
+
+/**
+ * Returns the global to prevent assigning values to 'this' when this is undefined.
+ * This can occur when files are interpreted by node in strict mode.
+ * @private
+ */
+function getGlobal() {
+    "use strict";
+
+    return typeof window !== "undefined" ? window : global;
```
Comment (mroderick) [inline lib/sinon/util/fake_xdomain_request.js]: If you modify this function to use `self` instead of `window`, then the code will not fail in Web Workers (where the `window` object is absent).

```javascript
return self || global;
```

Whether the rest of the file will work, I don't know.

Comment (Serfenia) [inline lib/sinon/util/fake_xdomain_request.js]: The tests don't fail currently. I just tried it using `self`, that works too. Shouldn't there be a test case for the web workers? Currently the tests pass without using `self`, so that means there is a missing test case for web workers, isn't there?

Comment (fatso83) [inline lib/sinon/util/fake_xdomain_request.js]: You are absolutely correct on that. I was wondering this myself yesterday. I have made a small test now that I will submit as a PR that will simply test if sinon works in a web worker.

**Comment by Serfenia** [comment]
Is there a reason why this is not yet merged to the 1.17 branch?

**Comment by fatso83** [comment]
Reason: We forget things ...

**Comment by fatso83** [comment]
Yup, as I suspected I had made the tests for WebWorker support in early November, but forgot to make a PR. I tested your changes on this test, and it passes, so I guess it must be good :-)
