### PR TITLE
Don't reset behavior when calling resetHistory()

### LINKED ISSUE #1361: `resetHistory` resets stubs behavior configured after `withArgs`
> We understand you have a problem and are in a hurry, but please provide us with some info to make it much more likely for your issue to be understood, worked on and resolved quickly.

* Sinon version : 2.1.0
* Environment : node 7.7.2
* Example URL : -
* Other libraries you are using: mocha 3.2.0, sinon-chai 2.9.0

**What did you expect to happen?**

Calling `resetHistory` should only reset the counters etc... not behaviors of a stub set after `withArgs`.

**What actually happens**

Calling `resetHistory` resets the return values set after `withArgs`

**How to reproduce**

```
// Setting behaviors
const sinon = require('sinon')
const test_stub = sinon.stub().returns(0);
test_stub.withArgs('test').returns(10);

// Testing everything's alright
test_stub(); // returns 0
test_stub('test'); // returns 10

// Breaking
test_stub.resetHistory();
test_stub(); // returns 0
test_stub('test'); // returns 0, shouldn't it be 10?
```

### PR DESCRIPTION
**Pull request by jroitgrund**
#### Purpose (TL;DR) - mandatory
Make `stub.resetHistory()` keep the behavior defined using `stub.withArgs(...).returns`.

#### Background (Problem in detail)  - optional
Fixes #1361

ATM `stub.resetHistory()` delegates to `spy.reset()` but `spy.reset()` resets all
its fakes by calling `reset()` on them. If the fakes were created from a
stub, we want to call `resetHistory()` on them instead to preserve their behavior.

#### How to verify - mandatory
Added a failing test so:

1. Check out this branch (see github instructions below)
2. `npm install`
3. `npm test`

### CODE REVIEW

**Comment by lucasfcosta** [comment]
LGTM, but maybe we could consider calling the `spy.reset` method `spy.resetHistory` in order to make it consistent with what it does and allow us to avoid this kind of check.

**Comment by Flarna** [comment]
I thought about the same as it would maybe solve also #1372. Unfortunately I found no time yet to try this by myself...

File: test/stub-test.js [hunk 1]
```diff
@@ -1991,6 +1991,15 @@ describe("stub", function () {
             assert(stub.calledOnce);
             assert.equals(stub.getCall(0).args[0], 2);
         });
+
+        it("doesn't reset behavior defined using withArgs", function () {
```
Comment (fearphage) [inline test/stub-test.js]: Please add a test for default behaviors (without `withArgs`).

**Comment by jroitgrund** [comment]
@fearphage done. anything else blocking this?

**Comment by fearphage** [comment]
@jroitgrund It looks clear to merge on my end. 

@sinonjs/sinon-core Would you like to do the honors?

**Comment by fatso83** [comment]
@fearphage You do have merge-rights, or have I screwed that up somehow? Because I think we totally trust you to not merge things willy-nilly :-)

**Comment by fearphage** [comment]
> You do have merge-rights, or have I screwed that up somehow?

I do, but I like to get a few sets of eyes on things. :smile:
