### PR TITLE
Fix issue #1964

### LINKED ISSUE #1964: callThrough doesn't work on a withArgs sub-stub
**Describe the bug**

#1442 was not fully fixed by #1549.  The case of using stubs directly instead of with mocks and expectations, as shown in https://github.com/sinonjs/sinon/issues/1442#issuecomment-306330402, is still broken.

**To Reproduce**
This code will throw an exception `TypeError: Cannot read property 'apply' of undefined` due to the fake returned from `withArgs` not having a `wrappedMethod` member.
```javascript
let stub = sinon.stub(obj, 'method')
	.withArgs(123)
	.returns('bar')
	.callThrough();
obj.method('bar')
```

**Expected behavior**
The `callThrough` behavior should be available on `withArgs` fakes.

**Screenshots**

**Context (please complete the following information):**

* Library version: Verified with `6.3.4` and `master` at `97a12178`
* Environment: Linux Node 10.x
* Example URL: N/A
* Other libraries you are using: N/A

**Additional context**

I've prepared a test case demonstrating the issue:
https://github.com/sinonjs/sinon/compare/master...mgabeler-lee-6rs:issue-1964

### PR DESCRIPTION
**Pull request by mgabeler-lee-6rs**
#### Purpose

Fix #1964 by adding a helper method to walk the stub parent links to find the `wrappedMethod` value for the `callsThrough` behavior.

 #### Background

If you try to use the `callsThrough` behavior on a `withArgs` stub, calling the stub with the matching args will fail, because the behavior fails to locate the original wrapped method to call through to.

This is effectively a followup to #1442 / #1549.

 #### Solution  - optional

A simple helper method walks up `stub.parent` links until it finds a `stub` that has a `wrappedMethod` member.

 #### How to verify - mandatory
1. Check out this branch
2. `npm install`
3. `npm test`, or just `npm run test-node`, or just `npm run test-node --grep 1964` to run the issue-specific test case

 #### Checklist for author

- [x] `npm run lint` passes
- [x] References to standard library functions are [cached](https://github.com/sinonjs/sinon/pull/1523).
  - N/A -- no standard library functions used

### CODE REVIEW

File: lib/sinon/behavior.js [hunk 1]
```diff
@@ -180,6 +181,15 @@ var proto = {
         return this.returnValue;
     },
 
+    effectiveWrappedMethod: function effectiveWrappedMethod() {
+        for (var stubb = this.stub; stubb; stubb = stubb.parent) {
+            if (stubb.wrappedMethod) {
+                return stubb.wrappedMethod;
+            }
+        }
+        return undefined;
```
Comment (fatso83) [inline lib/sinon/behavior.js]: I'd much prefer failing with an explit `Error` here telling us which assumption was wrong, rather than failing in the next step when ` wrappedMethod.apply` results in a null pointer exception.

```suggestion
        throw new Error("Unable to find wrapped method");
```

Comment (mgabeler-lee-6rs) [reply lib/sinon/behavior.js]: I had thought about that, but hadn't done it at first in the interest of minimizing changes to existing behavior.  But if you're in favor of it, then so am I :)

**Comment by fatso83** [comment]
Thanks!
