### PR TITLE
Check call count type

### LINKED ISSUE #2408: Asserting on callCount with a numeric string results in very confusing failure message
**Describe the bug**
This bug was originally reported in `sinon-chai` by @BebeSparkelSparkel as https://github.com/domenic/sinon-chai/issues/136 but turned out to be an issue with Sinon itself. The bug is that we can get the error message `AssertError: expected spy to be called 10 times but was called 10 times` - this happens when specifying `callCount` as a string.

**To Reproduce**
I made a slightly modified version of the original test case so that it just uses Sinon:
```
const sinon = require('sinon');
const n = '10',
      s = sinon.spy();
for(let i=0; i < n; ++i) s();

sinon.assert.callCount(s, n);
```

Run the above, you will get `AssertError: expected spy to be called 10 times but was called 10 times` which is a very confusing error message.

**Expected behavior**

One of two options:
 1. Sinon could coerce numeric strings into numbers, and pass the assertion
 2. Sinon could surface the actual problem, which is that callCount was not a number.

Both of these seem sensible, the first is a little more user-friendly, the second is a little more correct.

Internally it looks like Sinon raises a `TypeError`, which is I think what is actually triggering this failure, so it could just surface that, or it could attempt to convert to a number.

This actually happens with any string: `sinon.assert.callCount(s, 'banana')` will get you `expected spy to be called banana times but was called 10 times`, which is less confusing, but also it would probably be better to instead fail with an error about `banana` not being a number.

**Context (please complete the following information):**

- Library version: All versions (tested with most recent releases for v1-11, including 11.1.2)
- Environment: OS X
- Other libraries you are using: None

### PR DESCRIPTION
**Pull request by cincodenada**
#### Purpose (TL;DR)

Fix #2408 by checking the type of the argument to callCount and emitting a specfic error message if it is not a number

#### Details

I also refactored the assert tests a bit while I was here - the current code is manually removing the stack traces in each individual test, but since we already have a `message()` helper function to extract the message, I moved the stack trace stripping up into that, which streamlines the rest of the test cases quite a bit.

I also modified the regex to be more specific, and avoid accidentally stripping the end of messages that happen to have the word "at" in them.

#### How to verify

1. Check out this branch
2. `npm install`
3. Run the following test case:

```
const sinon = require('sinon');
const n = '10',
      s = sinon.spy();
for(let i=0; i < n; ++i) s();

sinon.assert.callCount(s, n);
```

You should get `expected '10' to be a number but was of type string`, rather than the current message which is `expected spy to be called 10 times but was called 10 times`

#### Checklist for author

- [x] `npm run lint` passes
- [x] References to standard library functions are [cached](https://github.com/sinonjs/sinon/pull/1523).

### CODE REVIEW

**Comment by cincodenada** [comment]
I would like to backport this to all current releases, as this bug exists in all released versions - what's the procedure for doing that? Should I just open a separate PRs for each version once this is approved?

**Comment by fatso83** [comment]
Truth be told, we don't have a procedure for backporting ... 🤔 This would involve creating release branches for every major release to accept PRs, so I think it might be just as fast just cherry picking it manually after merging. What would you suggest?

The biggest "consumer" is probably Sinon, and that is a bit more tricky to get right. Due to creating bundles it won't distribute the fix as efficiently.

**Comment by fatso83** [comment]
>  all current releases,

We don't actually have something like "LTS" releases, so in the sense that we need to support different use cases it would be:
- Sinon 1.x (if you really can't handle the breaking 2.x changes)
- Sinon 9 (if you cannot use ES2017+)
- Latest version

What versions would you like to fix this for? I would probably not bother with anything else than Sinon 7-12. I can probs do it if you are fine with that.

**Comment by cincodenada** [comment]
> EDIT: It was 3AM when I wrote this, so not everything makes sense in hindsight. I somehow mixed this with a PR in the fake-timers project.

Ha! No worries, and thanks, that part was a bit confusing 😅

I didn't have any grand designs on backporting, but I did get carried away ("this seems like the job for a simple bash script...") and backported it to all the versions - my fork [now has a `-backport` branch for each version](https://github.com/cincodenada/sinon/branches/all?query=backport), so feel free to grab from those whatever makes sense! It's certainly not a _critical_ issue, it just seemed like it's would be relatively easy to do, so the cost/benefit ratio was still low. I did end up backporting just the fix/test, and not the test refactoring.

**Review by fatso83 — CHANGES_REQUESTED** [review]
Wondering if the fixup of one comment actually turns right to wrong.

**Comment by fatso83** [comment]
Hi, Joel. I was about to do something about this which has been lingering for way too long, but then realized one of the commits might not be doing the right thing. Could you have a quick look at my comment and decide if I am right?

File: lib/sinon/proxy-call.js [hunk 1]
```diff
@@ -220,7 +220,7 @@ var callProto = {
             }
         }
         if (this.stack) {
-            // Omit the error message and the two top stack frames in sinon itself:
+            // Emit the error message and the two top stack frames in sinon itself:
```
[the remark this answers is not in the document]
Comment (cincodenada) [reply lib/sinon/proxy-call.js:223]: Okay, yes upon investigation you're totally right here, thanks, I misunderstood what was going on here. I read "in sinon itself" as "add the stack frame to sinon's output" when I now realize I think what it meant is "omit the top two stack frames, which will be in sinon itself".

After re-orienting myself, I do think it's a little confusing because if this code wasn't here, the stack frames wouldn't show up at all, and also because we're actually just pulling out only the third stack frame, rather than stripping off the first two and leaving the rest, right?

So the comment as it was is certainly better than my replacement, but what about something like:
```
          if (this.stack) {
            // If present, add the third stack frame to the error output for context
            // Skip the first two stack frames, which will be within Sinon code
            callStr += (this.stack.split("\n")[3] || "unknown").replace(
                /^\s*(?:at\s+|@)?/,
                " at "
            );
          }
```
(Code is the same, I just left it there for context)

[the remark this answers is not in the document]
Comment (fatso83) [reply lib/sinon/proxy-call.js:223]: Definitely an improvement!

File: test/proxy-call-test.js [hunk 2]
```diff
@@ -1176,29 +1176,44 @@ describe("sinonSpy.call", function () {
...
                 this.skip();
             }
 
             var stub1 = sinonStub().resolves(1);
             var stub2 = sinonStub().returns(1);
 
-            function run() {
-                return stub1().then(stub2);
-            }
+            await stub2(await stub1());
```
Comment (cincodenada) [inline test/proxy-call-test.js:1187]: This could be
```
const val = await stub1();
await stub2(val);
```
if that seems better, I couldn't decide which was less confusing 😄

File: lib/sinon/proxy-call.js [hunk 3]
```diff
@@ -220,7 +220,8 @@ var callProto = {
             }
         }
         if (this.stack) {
-            // Omit the error message and the two top stack frames in sinon itself:
+            // If we have a stack, add the first frame that's in end-user code
+            // Skip the first two frames because they will refer to Sinon code
```
Comment (cincodenada) [inline lib/sinon/proxy-call.js:224]: I put this through another round of editing, hopefully this is still clear

File: test/proxy-call-test.js [hunk 4]
```diff
@@ -1176,29 +1176,44 @@ describe("sinonSpy.call", function () {
...
+            object.doIt();
+
+            const [name, stackFrame] = object.doIt
+                .getCall(0)
+                .toString()
+                .split(" at ");
+
+            assert.equals(name, "doIt()");
+            assert.contains(stackFrame, __filename);
+        });
```
Comment (cincodenada) [inline test/proxy-call-test.js:1216]: This test should make sure we're always returning the first end-user stack, even if the internals change. I use `__filename` here because for the test's purposes `proxy-call-test.js` is the "end-user" code, and the variable ensures we're safe from renames or what have you. Let me know if that seems unreasonable/weird.

File: test/proxy-call-test.js [hunk 5]
```diff
@@ -1176,29 +1176,44 @@ describe("sinonSpy.call", function () {
 
         // https://github.com/sinonjs/sinon/issues/1066
         /* eslint-disable consistent-return */
-        it("does not throw when the call stack is empty", function (done) {
+        it("does not throw when the call stack is empty", async function () {
```
Comment (cincodenada) [inline test/proxy-call-test.js:1179]: This test doesn't have anything to do with the rest of the PR, other than being next to the test I was adding.

I figured since it's just in tests async should be fine to use, but I also just did a search and realized the only other async tests are in `promise-test.js` and an es2015-specific test, so if y'all don't do async tests generally, let me know and I'll revert this bit.

**Comment by cincodenada** [comment]
Okay, thanks for catching the comment - I decided to go ahead and add a test for the frame-appending bit too, since I didn't see one already, and converted a test to async while I was there. At this point the test cleanup outweighs the original fix I think, so if it makes more sense to split this into two PRs, let me know and I can rewrite accordingly, ha!

File: test/proxy-call-test.js (hunk 2 above)
Comment (fatso83) [reply test/proxy-call-test.js:1187]: TBH I find Promise chaining much more understandable, as in `await stub1().then(stub2)`, but I do not really care all that much either :p Whatever rocks your boat :)

File: test/proxy-call-test.js (hunk 5 above)
Comment (fatso83) [reply test/proxy-call-test.js:1179]: We just changed target browsers to evergreen last year, so it's not all that much that has changed since. Adding `async` is fine, as I believe ES2018 is our current ES level.

**Review by fatso83 — APPROVED** [review]

**Comment by fatso83** [comment]
Great stuff, thanks for the addition!

**Comment by fatso83** [comment]
Ajajaj, seems that did not pan out that well as it failed when running the browser tests on SauceLabs. These 11 breaking tests are for Firefox:
```
  1464 passing (3s)
  13 pending
  11 failing

  1) assert
       message
         assert.notCalled exception message one call:

      [assert.equals] 'expected doSomething to not have been called but was called once\n    doSomething() at callFn@about:blank line 2 > injectedScript:47353:21' expected to be equal to 'expected doSomething to not have been called but was called once\n    doSomething()'
      + expected - actual

       expected doSomething to not have been called but was called once
      -    doSomething() at callFn@about:blank line 2 > injectedScript:47353:21
      +    doSomething()
      
  fail@about:blank line 2 > injectedScript:8641:21
  fail@about:blank line 2 > injectedScript:8801:17
  assertion@about:blank line 2 > injectedScript:8819:11
  defineAssertion/referee[type][name]@about:blank line 2 > injectedScript:8846:22
  require<[248]</</</<@about:blank line 2 > injectedScript:25036:20
      -    doSomething(1, 3, 'hey') at callFn@about:blank line 2 > injectedScript:47353:21
      -    doSomething(1, 3) at callFn@about:blank line 2 > injectedScript:47353:21
      +    doSomething(1, 3, 'hey')
      +    doSomething(1, 3)
      
  fail@about:blank line 2 > injectedScript:8641:21
  fail@about:blank line 2 > injectedScript:8801:17
  assertion@about:blank line 2 > injectedScript:8819:11
  defineAssertion/referee[type][name]@about:blank line 2 > injectedScript:8846:22
  require<[248]</</</<@about:blank line 2 > injectedScript:25748:20
  callFn@about:blank line 2 > injectedScript:47353:21
  require<[277]</<[32]</</Runnable.prototype.run@about:blank line 2 > injectedScript:47345:13
  require<[277]</<[33]</</Runner.prototype.runTest@about:blank line 2 > injectedScript:47881:10
  next/<@about:blank line 2 > injectedScript:47999:12
  next@about:blank line 2 > injectedScript:47795:14
  next/<@about:blank line 2 > injectedScript:47805:11
  next@about:blank line 2 > injectedScript:47729:14
  next/<@about:blank line 2 > injectedScript:47768:11
  done@about:blank line 2 > injectedScript:47300:7
  callFn@about:blank line 2 > injectedScript:47376:7
  require<[277]</<[32]</</Runnable.prototype.run@about:blank line 2 > injectedScript:47345:13
  next@about:blank line 2 > injectedScript:47743:10
  require<[277]</<[33]</</Runner.prototype.hook/<@about:blank line 2 > injectedScript:47773:9
  timeslice@about:blank line 2 > injectedScript:42885:27
  

  11) assert
       message
         assert.alwaysThrew exception message:

      [assert.equals] 'doSomething did not always throw exception\n    doSomething(1, 3, \'hey\') at callFn@about:blank line 2 > injectedScript:47353:21\n    doSomething(1, 3) at callFn@about:blank line 2 > injectedScript:47353:21' expected to be equal to 'doSomething did not always throw exception\n    doSomething(1, 3, \'hey\')\n    doSomething(1, 3)'
      + expected - actual

       doSomething did not always throw exception
      -    doSomething(1, 3, 'hey') at callFn@about:blank line 2 > injectedScript:47353:21
      -    doSomething(1, 3) at callFn@about:blank line 2 > injectedScript:47353:21
      +    doSomething(1, 3, 'hey')
      +    doSomething(1, 3)
      
  fail@about:blank line 2 > injectedScript:8641:21
  fail@about:blank line 2 > injectedScript:8801:17
  assertion@about:blank line 2 > injectedScript:8819:11
  defineAssertion/referee[type][name]@about:blank line 2 > injectedScript:8846:22
  require<[248]</</</<@about:blank line 2 > injectedScript:25758:20
  callFn@about:blank line 2 > injectedScript:47353:21
  require<[277]</<[32]</</Runnable.prototype.run@about:blank line 2 > injectedScript:47345:13
  require<[277]</<[33]</</Runner.prototype.runTest@about:blank line 2 > injectedScript:47881:10
  next/<@about:blank line 2 > injectedScript:47999:12
  next@about:blank line 2 > injectedScript:47795:14
  next/<@about:blank line 2 > injectedScript:47805:11
  next@about:blank line 2 > injectedScript:47729:14
  next/<@about:blank line 2 > injectedScript:47768:11
  done@about:blank line 2 > injectedScript:47300:7
  callFn@about:blank line 2 > injectedScript:47376:7
  require<[277]</<[32]</</Runnable.prototype.run@about:blank line 2 > injectedScript:47345:13
  next@about:blank line 2 > injectedScript:47743:10
  require<[277]</<[33]</</Runner.prototype.hook/<@about:blank line 2 > injectedScript:47773:9
  timeslice@about:blank line 2 > injectedScript:42885:27
```

**Comment by fatso83** [comment]
@cincodenada any chance of having a look at the Firefox issue? Otherwise I need to revert the change to unblock releases.

**Comment by cincodenada** [comment]
@fatso83 Yes, sorry I intended to get to this yesterday and then got sidetracked. I'll take a look this evening (Pacific Time) - is there a way for me to run the tests in Firefox myself? If not that's fine, I'm sure I can reproduce manually, but if there's an easier way I'll take it 😄

And as a Firefox user myself, I appreciate SauceLabs' dilligence!

**Comment by cincodenada** [comment]
Okay, yeah I see what's happening here, should hopefully be a pretty simple fix - I wasn't able to test against Firefox yet, but after investigating the issue seems clear enough that I put up #2425, which reverts a small part of this PR that is causing the Firefox tests to fail, due to Firefox having a different stack trace format that breaks some assumptions I had made.
