### PR TITLE
Fix  #1801: spied fakeTimers are not restored correctly

### LINKED ISSUE #1801: Spied fakeTimers are not restored correctly
**Describe the bug**
When a fakeTimer is spied, `sandbox.restore()`/`sinon.restore()` does not restore `setTimeout` to the original function. 

Related to: #1775, #1780

**To Reproduce**

```javascript
it("restores spied fake timers when then sanddox is restored", function () {
    var originalSetTimeout = setTimeout;

    this.sandbox.useFakeTimers();
    this.sandbox.spy(global, "setTimeout");

    this.sandbox.restore();

    assert.same(originalSetTimeout, global.setTimeout, "fakeTimers restored");
});

it("should restore spied fake timers", function () {
    var originalSetTimeout = setTimeout;

    sinon.useFakeTimers();
    sinon.spy(global, "setTimeout");

    sinon.restore();

    assert.same(originalSetTimeout, global.setTimeout, "fakeTimers restored");
});

```

**Expected behavior**
Tests above should pass.

**Context (please complete the following information):**

* Library version: 5.0.7
* Environment: OSX, node 8.10.0

### PR DESCRIPTION
**Pull request by ifrost**
#### Purpose (TL;DR) - mandatory

When a fakeTimer is spied, sandbox.restore()/sinon.restore() does not restore setTimeout to the original function.

#### Background (Problem in detail) 

See #1801

When `sandbox.useFakeTimers()` is called, the original `setTimeout` and other methods are replaced with fake methods. When such fake method is spied it's replaced again with another fake. To make sure that `sandbox.restore()` reverts `setTimeout` and other methods to the original state these fakes should be restored in reverse order to make sure each fake is restored to its predecessor when calling fake.restore().

What is more the default sandbox doesn't use `sandbox.useFakeTimers`(see also #1775) and `sandbox.clock` (see #1780). To make the fix work in default sandbox it should pass `useFakeTimers` through to the sandbox method. Using `sandbox.clock` in the default sandbox added for consistency. 

#### How to verify - mandatory
1. Check out this branch
2. `npm install`
3. `npm test`

### CODE REVIEW

File: lib/sinon.js [hunk 1]
```diff
@@ -24,11 +24,8 @@ var apiMethods = {
     setFormatter: format.setFormatter,
 
     // fake timers
-    useFakeTimers: fakeTimers.useFakeTimers,
```
Comment (fatso83) [inline lib/sinon.js]: So these lines that were hanging around from earlier versions essentially shadowed the new sandbox functions on the prototype. Good find!

**Comment by fatso83** [comment]
Thanks for the fix and the work put in! Out as 5.0.10

**Comment by mroderick** [comment]
Thank you for the contribution @ifrost 💯
